### PR TITLE
Added cd and mkdir commands

### PR DESCRIPTION
**Pull request by SarahMalykke**
@jessb0t let me know if I made the correct edits - I added cd and mkdir commands

### CODE REVIEW

**Comment by jessb0t** [comment]
@SarahMalykke
FYI, you can "assign" this review to me officially by selecting me from the dropdown here, on the right-hand side of the pull request page:
image

(Not required, especially since we're chatting live about these things today. Just letting you know for the future!)

**Comment by SarahMalykke** [comment]
Got it! Will do that next time!

**Comment by jessb0t** [comment]
@SarahMalykke 
Thank you for this!  I have a few little concerns... 🤓 
1. Location: I had thought you wanted to provide some information specifically on how to create the "github" directory on your root during setup, which is why I suggested the Git + GitHub page.  But these commands are not Git commands, they're actually Shell commands (and already exist [here](https://ndclab.github.io/wiki/docs/technical-docs/shell.html#important-commands)).  If you think these need some sprucing, please update on the Shell page.  And I still think your idea about explicit help for `mkdir github` will be helpful on the Git+GitHub page. You'd probably need to create a new section after Authenticating that is specific to setting up a central place for storing all your git initialized folders?
2. Examples: In your examples, you use brackets for naming.  I think it would be better to provide an actual example name, and then you can use the hash to comment it out, like this:

```sh
# to move from a higher-level directory into the "important-folder" directory
cd important-folder
```

**Comment by SarahMalykke** [comment]
Oh I see what you mean! No need to make any changes then 😅 @jessb0t

**Comment by jessb0t** [comment]
But, @SarahMalykke, I really think you had a good idea!  You hit that roadblock about how to set up your "github" folder on your local, and I'm sure you won't be the last!  A little explanation and how-to on the Git+GitHub page really would be an excellent addition!

**Comment by jessb0t** [comment]
@SarahMalykke Just reminding you that I still think this is a great idea, just in a different location (see above).  Feel free to modify either by changing the branch on your local (use `git status` to check which branch you're on -- if not `feature-mkdirGitHub-sarah`, use `git checkout` to switch) or by modifying the file directly on GitHub.  Arina can show you how as she and I did that yesterday today for a branch she was working on! 🙌

**Comment by jessb0t** [comment]
Replaced by #123.

**Pull request closed without merging**
