### PR TITLE
Add Ioanna to who's-who

### PR DESCRIPTION
**Pull request by IoannaPapadaki**
Hey @jessb0t ! Please review my update to the wiki! Thank you!

### CODE REVIEW

**Comment by jessb0t** [comment]
Thanks, @IoannaPapadaki !  The syntax looks good...but it should be "papadaki" not "ioanna". 😉 

For some reason, your changes to the whos-who.md file are displaying strangely in GitHub.  I think it might be something to do with the text editor you are using.  Out of curiosity, which one is that?  I don't think you're doing anything wrong on that so we'll try to merge anyway and I'll let you know if it causes problems!

Also, just a note that you do not need to create a new pull request each time.  Once you have a PR open, you can address any commits on the underlying branch and then simply add a new comment to the existing PR to bring my attention to it!

Let me know if you have any questions!

**Comment by IoannaPapadaki** [comment]
> Thanks, @IoannaPapadaki ! The syntax looks good...but it should be "papadaki" not "ioanna". 😉
> 
> For some reason, your changes to the whos-who.md file are displaying strangely in GitHub. I think it might be something to do with the text editor you are using. Out of curiosity, which one is that? I don't think you're doing anything wrong on that so we'll try to merge anyway and I'll let you know if it causes problems!
> 
> Also, just a note that you do not need to create a new pull request each time. Once you have a PR open, you can address any commits on the underlying branch and then simply add a new comment to the existing PR to bring my attention to it!
> 
> Let me know if you have any questions!

I used an app called


> Thanks, @IoannaPapadaki ! The syntax looks good...but it should be "papadaki" not "ioanna". 😉
> 
> For some reason, your changes to the whos-who.md file are displaying strangely in GitHub. I think it might be something to do with the text editor you are using. Out of curiosity, which one is that? I don't think you're doing anything wrong on that so we'll try to merge anyway and I'll let you know if it causes problems!
> 
> Also, just a note that you do not need to create a new pull request each time. Once you have a PR open, you can address any commits on the underlying branch and then simply add a new comment to the existing PR to bring my attention to it!
> 
> Let me know if you have any questions!


I used an app called desktop note. I should my picture's name right? I hope they will be no issues because I worked on this for like 30 minutes haha. If it doesn't work, what app should I use instead that works with both windows and github?

**Comment by jessb0t** [comment]
@IoannaPapadaki Yes, please correct the file name (and its reference) for your photo.  Thanks!

In terms of applications, I believe that Notepad is safe!  (But don't stress about that part until we try to merge.  I think it might just be a simple display issue.)

**Comment by jessb0t** [comment]
@IoannaPapadaki Following up on this PR when you have a chance.  Thank you!

**Pull request closed without merging**
