### PR TITLE
Add Arina to who's-who

### PR DESCRIPTION
**Pull request by apoly1**
Hi @jessb0t hope all is well! I have added my info for who's-who page, please review it. Thank you!
P.S. your tutorial is awesome!

### CODE REVIEW

**Comment by jessb0t** [comment]
@apoly1 This looks great!  Before I merge, though, I suggest that you change the file name of your photo to be "polyanskaya" (rather than "Polyanskaya") because GitHub is sometimes case sensitive.  You can do this on your "whos-who-arina" branch.  When you do this, you'll see two changes to commit: a deletion and an addition.  You'll want to commit both, then push back to the remote.  Let me know if you have any trouble and please re-@ me when you're ready for me to merge!

**Comment by georgebuzzell** [comment]
@apoly1 @jessb0t Just checking in on this: I think I am not supposed to review this PR, right? This one was supposed to be closed and a new (fixed) one opened?

**Comment by jessb0t** [comment]
@georgebuzzell You are correct: there is no need for you to review this.  @apoly1 is working on this and I will be providing guidance as necessary! :)

**Review by jessb0t — APPROVED** [review]
@apoly1 Looks great!  Merging now! 😎

**Pull request merged**
