### PR TITLE
Add Anfernee to who's who

### PR DESCRIPTION
**Pull request by adunc018**
Hi @jessb0t ! Please review my update for the wiki. Thank you!

### CODE REVIEW

**Comment by jessb0t** [comment]
@adunc018 Thank you!  Everything looks almost perfect! 😉  The only little thing is that you put yourself down in the Junior Research Technicians (after Osmany), whereas you should be up in the Junior Research Assistants section.  You just need to cut and paste your content to the right location, leaving nice spacing between!

You can make that change on your local (on the same branch!), add to your staging area, commit, and do a new "git push origin whos-who-Anfernee" to propagate your change up here to the remote.  Once that is done, please add a new comment here to @mention me, so that I know to check again!  Thank you!

(Side note: you also used a capital in your branch name.  Do not try to change this as it is not worth the hassle (trust me, I've been there before!!!), but please just use lowercase naming conventions for GitHub branches going forward.  Thanks!)

**Comment by adunc018** [comment]
Hey @jessb0t ! I think I got it this time but I'm not 100% sure. Can you review my addition again please? Also I'll be sure to watch out for using caps in the branch names from now on because I just spent 15 minutes trying to figure out why the changes wouldn't push before realizing the branch had a capital A in it 😭

**Review by jessb0t — APPROVED** [review]
Awesome job, @adunc018 !  For the future, think about making each of your commits more informative.  So the first one was great, but the second one could have been something like "Fix order of who's who". :wink:

**Comment by jessb0t** [comment]
@adunc018 Merging now!

**Pull request merged**
