### PR TITLE
Created instruments tech page

### LINKED ISSUE #189: Create instruments page

### PR DESCRIPTION
**Pull request by F-said**
## Changes Made
**Technical**: added initial instruments page providing light guidance to instruments

## Checklist
- [X] All my proposed changes have been pushed to the remote.
- [X] This pull request is showing as a merge into `main`.
- [X] I have assigned a specific reviewer for this pull request.
- [X] I have connected any associated issues to this pull request so they will be automatically closed when the PR is merged.

## Notes
Resolve #189

### CODE REVIEW

**Comment by jessb0t** [comment]
@F-said I did a heavy re-write to interconnect existing wiki pages.  I don't think we need the contributing stuff, because our CONTRIBUTING.md file already links to [this page](https://ndclab.github.io/wiki/docs/contributing.html).  Also, I deleted the stuff about using local because we really want lab members to run this on the HPC.

To that end, could you please flesh out the section on preprocessing?  For instance, I don't know what "SSH into" really means (how to execute).  And it would be helpful to give pointers on how to set up input/output paths (later we can automate them, of course).

Also, it would be great to know how to checkout the dev branch on the HPC in order to run an output on a new instrument in order to test it before PRing to main.

Let me know if you have any questions! :pray:

**Comment by F-said** [comment]
@jessb0t ty for the feedback! Incorporated directions on how to process data on the HPC.

**Comment by jessb0t** [comment]
@F-said I added some screenshots to help.  I wasn't sure if this instruction was still valid?

image

That is, perhaps it is easiest for the more tech-savvy but if someone like me or a project lead were to log in like we demo-ed on Friday, would this still be a required step?

**Comment by F-said** [comment]
@jessb0t Yeah that's "legacy" instruction, removed. Thanks for the changes! Fleshed out step #4. LMK what you think.

**Review by jessb0t — APPROVED** [review]

**Comment by jessb0t** [comment]
@F-said Added some final suggestions!

**Comment by F-said** [comment]
@jessb0t TY. Added some md formatting and merging!

**Pull request merged**
