### PR TITLE
Main page pepper tech

### LINKED ISSUE #120: Create wiki entry for PEPPER
Include

- tutorial
- planning docs, motivation
- roadmap

### PR DESCRIPTION
**Pull request by F-said**
- Extracted out CONTRIB/README
- Included planning documents from drive
- Fleshed out contrib directions 
- Resolve #120

### CODE REVIEW

**Comment by F-said** [comment]
Hi @jessb0t , whenever you have time, could you give `pepper-usage.md` a look-through?

**Comment by jessb0t** [comment]
@F-said : Could you give me some background on the intent here?  Is this replacing the content from readme/contrib of the PEPPER repo itself?  Or is it a duplicate?  If duplicating, what is the advantage to having the content in both places (versus pointing wiki to repo, for instance)?  I just want to make sure that I understand your intent before I dive in! 🙏

**Comment by F-said** [comment]
@jessb0t Thanks for the question! This wiki entry basically takes from the [contrib](https://github.com/NDCLab/pepper-pipeline/blob/dev-readme-update/CONTRIBUTING.md) & [readme](https://github.com/NDCLab/pepper-pipeline/tree/dev-readme-update) to shorten both of these documents. There will still be content in both docs, but they'll only contain the bare necessities.

**Comment by jessb0t** [comment]
@F-said 

I committed a few mini changes on your branch.  Here are the more detailed thoughts/notes for you to review and use as you wish! 🤠 

- Suggestion: you may to check nav order as I believe we added the Zotero page after you made this dev branch.
- I'm not quite sold on the naming of the section entitled "Planning Docs"...but I don't have an immediate suggestion.
- In "Planning Docs," both `` and "" are used to offset "user_params.json" and "output_preproc.json".  It's unclear to me whether the distinction is intentional.  If intentional, leave it be!  Just mentioning in case it wasn't intentional.
- You use both "high pass" and "high-pass."  I don't know which is standard?  My eye likes "high-pass" better, but we should use whatever is standard in the field.
- In "Final Reject Epochs," would it be accurate to change "If it exceeds the threshold, reject the channel data for this channel/epoch." to "If it exceeds **either** threshold, reject the channel data for this channel/epoch."?
- Under "Development Guidelines," I wonder if "Submit an Issue" should be re-characterized as Report a Bug/Request a Feature?  I say that because "Create Documentation" is also, technically, the submission of an issue.  But then I don't like "Report a bug/request a feature" because it implies that someone else will do it rather than giving the sense that you are recording something that you think is a good idea and you're going to start working on.  Maybe we drop the red box in the image and re-jig this to "Identify Issues or Enhancements", then combine Submit an Issue and Create Documentation?
- Contribute to the Code: can someone begin working on an issue that they created? How do they assign themselves so others will know it is in progress?  (Or are external people not supposed to do that...do they have to wait until their fork is ready to pull?)
- In the cloning instructions, I deleted the "/" in the cd command because I don't think it's necessary?  But feel free to put it back if I'm wrong!
- Do you really need to do git fetch before git checkout dev-feature-issue?  Since you just cloned the repo, won't checking out the branch have the same effect?  (Sorry, I don't really know what git fetch does because I've never used it.)
- If someone is working on an active branch, shouldn't they also create their own named branch?  This specifies that requirement for creating a new feature branch but not working on an existing one.
- The git commit message example doesn't follow our conventions. 😉   I think it should be "Attach flux capacitor" (in the imperative).
- Will git push at the end there work?  I always do git push origin branch-name.

**Pull request closed without merging**
