### PR TITLE
Add Brandon to who's-who

### PR DESCRIPTION
**Pull request by beadleson**
Hey @jessb0t  ! Please review my update to the wiki. Thanks!

### CODE REVIEW

**Comment by jessb0t** [comment]
@beadleson Overall, looks great!  Could I just request that you switch the jpg file name to "beadleson"?  Thank you!

**Comment by beadleson** [comment]
Updated Branch with brandon.jpg with beadleson.jpg

**Comment by jessb0t** [comment]
Thanks, @beadleson !  I think you'll also need to update the call in the whos-who.md file now to match the new filename. ;)

**Comment by beadleson** [comment]
New path with updated name beadleson.jpg on .md file

**Review by jessb0t — APPROVED** [review]
Thanks, @beadleson !  Merging now!

**Pull request merged**
