### PR TITLE
Added hpc-docs

### PR DESCRIPTION
**Pull request by F-said**

### CODE REVIEW

**Comment by F-said** [comment]
Thanks for the review! Re-requesting once completed suggested edits @jessb0t

**Comment by jessb0t** [comment]
@F-said 
I still see some links with this path:
https://raw.githubusercontent.com/NDCLab/wiki/gh-pages/docs/_assets/hpc

I think we just need to switch "gh-pages" for "main" and they'll connect properly at publication.

**Comment by jessb0t** [comment]
@F-said : Sorry, I just switched the structure a bit.  HPC will now be nav page 4. 🙄

**Comment by F-said** [comment]
Created the following diagrams to represent access levels. In future branch might create separate page to reduce length of hpc documentation:

https://user-images.githubusercontent.com/26397102/122823863-dfbfdb80-d2ad-11eb-94b8-daf9a585f890.png

**Review by jessb0t — APPROVED** [review]
@F-said This is awesome!  Love the visual for the data structure!  I pushed a few minor changes to correct tiny typos.  The only other note I have before you merge (which I would prefer that you do since there are conflicts, haha), is that some of the later images for Jupyter look stretched kind of weird.  Maybe there's an easy way to fix that?

**Comment by georgebuzzell** [comment]
> Created the following diagrams to represent access levels. In future branch might create separate page to reduce length of hpc documentation:
> 
> NDCLab Privilges
> 
> colorcode

@F-said I love this visual!!

**Comment by F-said** [comment]
@jessb0t 
- Resolved merge conflict
- added docs
- fixed image size

**Review by jessb0t — APPROVED** [review]
Thank you, @F-said!  I corrected a few little punctuation things to polish it up.  Merging now!

**Pull request merged**
